### PR TITLE
Add access request URL generator

### PR DESCRIPTION
**Pull request by lpww**
Simple URL generator. Added extra 'type' parameter to setupRequestURL in order to reuse the function.

### CODE REVIEW

**Comment by iamstuartwilson** [comment]
Nice! As a workflow, I'd recommend just branching off the organisation branch rather than forking, than way you don`t have to keep two local copies.

**Comment by lpww** [comment]
Cool, that's a good idea!

**Comment by iamstuartwilson** [comment]
Cool, merged dude.  Do you know anything about Travis CI?  I'll write some tests tomorrow and show you the beauty of CI.  Basically it adds a build step so you can be assured that code works before merging :+1:

**Comment by iamstuartwilson** [comment]
We should also start a slack channel for work on this.

**Comment by lpww** [comment]
I've never used travis specifically but I've done the same thing using codeship with jasmine/karma

**Comment by lpww** [comment]
Also added the slack channel and invited you

**Pull request merged**
